### PR TITLE
"Shelters Needing Updates" view fixes

### LINKED ISSUE #24: Make `state` field visible in "Shelters Needing Updates" view

### LINKED ISSUE #25: Fix default sort in "Shelters Needing Updates" view to show most outdated first

### LINKED ISSUE #26: Enable "Shelters Needing Updates" as a JSON endpoint
Something like `/api/v1/shelters/outdated` or `/api/v1/shelters?outdated=true`

### PR DESCRIPTION
**Pull request by nihonjinrxs**
This does the following:

- Adds the `state` column to the Shelters Needing Updates view (and to all others) - closes #24 
- Fixes the default sort view on the Shelters Needing Updates view - closes #25 
- Enables a JSON API endpoint for Shelters Needing Updates at `/api/v1/shelters/outdated` - closes #26 

Review appreciated. These are pretty simple fixes, so I don't expect anything to break.

### CODE REVIEW

File: app/controllers/api/v1/shelters_controller.rb [hunk 1]
```diff
@@ -5,43 +5,56 @@ class Api::V1::SheltersController < ApplicationController
...
 
   def index
-    @filters = {}
-    @shelters = Shelter.all
+    @shelters, @filters = apply_params(Shelter.all, params)
+  end
+
+  def outdated
+    @outdated, @filters = apply_params(
+      Shelter.where("updated_at < ?", 4.hours.ago).order('updated_at DESC'),
```
Comment (omnilord) [inline app/controllers/api/v1/shelters_controller.rb]: Just some food for thought (not a review).  This query is a good candidate for a scope `Shelter.outdated`.  The definition would be placed in the Shelter model after the after_commit callback:
```Ruby
scope :outdated, ->(timing = 4.hours.ago) { where("updated_at < ?", timing) }
```

File: app/views/api/v1/shelters/outdated.json.jbuilder [hunk 2]
```diff
@@ -0,0 +1,13 @@
+json.cache! @outdated do
```
Comment (omnilord) [inline app/views/api/v1/shelters/outdated.json.jbuilder]: I don't see any configuration for a cache expiration time.  Unless I have missed it (very possible) `json.cache!` will cache indefinitely.  Adding an `expires_in` parameter is probably smart.  Also, how do we invalidate the cache if an update is made before expiration?

Comment (omnilord) [reply app/views/api/v1/shelters/outdated.json.jbuilder]: Also curious about why you didn't keep `@shelters` as the variable.  Would have allowed you to keep the same variable for apply_params function instead of replaces the instance variables with local variables.

File: app/controllers/api/v1/shelters_controller.rb [hunk 3]
```diff
@@ -5,43 +5,56 @@ class Api::V1::SheltersController < ApplicationController
...
+      params
+    )
+  end
+
+  private
+
+  def apply_params(shelters, params)
```
Comment (omnilord) [inline app/controllers/api/v1/shelters_controller.rb]: You don't need to pass params here, the params object is accessible anywhere in the controller.

File: app/views/api/v1/shelters/outdated.json.jbuilder (hunk 2 above)
Comment (nihonjinrxs) [reply app/views/api/v1/shelters/outdated.json.jbuilder]: Started out trying to be explicit, and things got deeper and deeper. I may switch this back and clean that up. I do like the refactoring of `apply_params`, so I'll likely keep that anyway.

Regarding cache, I'm just mimicking what's there already. I agree we should probably look at that, but I think that's a new issue unrelated to this, and should have it's own PR.

File: app/controllers/api/v1/shelters_controller.rb (hunk 3 above)
Comment (nihonjinrxs) [reply app/controllers/api/v1/shelters_controller.rb]: Sorry, all my work with functional languages coming through. Will fix.

File: app/controllers/api/v1/shelters_controller.rb (hunk 1 above)
Comment (nihonjinrxs) [reply app/controllers/api/v1/shelters_controller.rb]: Nice, hadn't used those before. I'll take a look at that.

**Comment by nihonjinrxs** [comment]
OK, I think things here are ready to go. Appreciate a review, and if there's nothing else to do, an approval. Thanks!
